### ISSUE TITLE
CSS variables

### ISSUE THREAD

**Issue by tinovyatkin** [csstree/stylelint-validator#1]
CSS variables is valid syntax supported by major browsers and with spec, however, it marked by module as invalid.

Some links:
http://caniuse.com/#search=css%20variables
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by lahmatiy** [comment]
Fixed. Try update to [`1.0.3`](https://github.com/csstree/stylelint-validator/releases/tag/v1.0.3)

**Comment by tinovyatkin** [comment]
Works great, thank you for fast fix!
