### ISSUE TITLE
Invalid value for `color`   csstree/validator in SCSS

### ISSUE THREAD

**Issue by jitendravyas** [csstree/stylelint-validator#10]
`color: darken(white, 5%);`

**Comment by boyum** [comment]
Same for `color: rgba(#fff, 0.5);`.

**Comment by lahmatiy** [comment]
Since [1.9.0](https://github.com/csstree/stylelint-validator/releases/tag/v1.9.0) became possible to extend syntax definition with `types` and `properties` options.

For your examples, try this:
```json
{
  "plugins": [
    "stylelint-csstree-validator"
  ],
  "rules": {
    "csstree/validator": {
      "types": {
        "color": "| darken(<color>, <percentage[0,100]>)",
        "rgba": "| rgba(<hex-color>, <number[0,1]>)"
      }
    }
  }
}
```

**Comment by amanuelbelete95** [comment]
I have this in my stylelintrc file but it still having the problem
