### ISSUE TITLE
Missing error on `appearance` property

### ISSUE THREAD

**Issue by pkuczynski** [csstree/stylelint-validator#12]
I the SCSS I was validating someone used `appearance` property, which according to different sources ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance), [Can I Use](https://caniuse.com/#search=appearance)) always requires `moz-` or `webkit` prefix.

I believe this is a bug, which would need fixing? 

I might try to provide a PR after your confirmation, that this is an issue.

**Comment by lahmatiy** [comment]
Most browsers are supported for non prefixed version of `appearance`. Closing since it not an error.
