### ISSUE TITLE
Compatibility with stylelint 10?

### ISSUE THREAD

**Issue by acdha** [csstree/stylelint-validator#16]
Currently there's a peer dependency on stylelint < 10 which prevents usage with current versions of a growing number of projects.

**Comment by lahmatiy** [comment]
We need to try it with stylelint 10 and bump version if everything is ok. PR is welcome

**Comment by lahmatiy** [comment]
Support added in [1.4.0](https://github.com/csstree/stylelint-validator/releases/tag/v1.4.0)
