### ISSUE TITLE
Getting some weird output ok ?? 36 ok ?? 36 ok ?? 36

### ISSUE THREAD

**Issue by limonte** [csstree/stylelint-validator#18]
This issue is forwarded from https://github.com/stylelint/stylelint/issues/4146

In https://github.com/stylelint/stylelint/issues/4146#issuecomment-508876736 @hudochenkov narrowed down the issue is coming from `stylelint-csstree-validator`.

---

> Clearly describe the bug

I'm getting some weird output when running `stylelint src/**/*.scss`:

```
ok
?? 36
ok
?? 36
ok
?? 36
ok
?? 36
```

Live demo: https://travis-ci.org/sweetalert2/sweetalert2/builds/554841887

> What stylelint configuration is needed to reproduce the bug?

https://github.com/sweetalert2/stylelint-config/blob/master/index.js

> Which version of stylelint are you using?

`10.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`stylelint src/**/*.scss`

> What did you expect to happen?

No weird output.

### Steps to reproduce 

1. `git clone https://github.com/sweetalert2/sweetalert2.git`
2. `cd sweetalert2`
2. `yarn install`
3. `./node_modules/.bin/stylelint src/**/*.scss`

OS: Linux, 
node version: 12.5.0

**Comment by lahmatiy** [comment]
Woops... missed `console.log()` in the source. Sorry about this, fixing ASAP.

**Comment by lahmatiy** [comment]
Fixed in [1.4.1](https://github.com/csstree/stylelint-validator/releases/tag/v1.4.1).

**Comment by limonte** [comment]
Thank you @lahmatiy for the prompt fix!
