### ISSUE TITLE
Ignoring Less variables

### ISSUE THREAD

**Issue by notethis** [csstree/stylelint-validator#3]
I took this lovely plugin for a whirl today, it correctly discovered some issues where my team had written invalid syntax, however the majority of the errors it reported was the `csstree/validator` rule choking on Less variables, ex:
```
src/Component/Component.less
 28:13  ✖  Can't parse value "@link-hover-color"   csstree/validator
 54:9   ✖  Can't parse value "@icon-color"         csstree/validator
```
Any idea how to mute or ignore Less variables (I'm assuming the same goes for Sass variables). 

Thanks!

**Comment by lahmatiy** [comment]
Hi @notethis!

Could you provide an example of such rule?
Yep, I think we can add an ignore rule for these declarations.

**Comment by lahmatiy** [comment]
Something like that?

```
#header {
  color: @icon-color;
}
```

**Comment by notethis** [comment]
Yep! Standard less syntax:
```
.foo:hover {
   color: @link-hover-color; 
   padding: @link-padding 0;
}
etc.

**Comment by lahmatiy** [comment]
Ok. Will take a look later. As first step I'll mute those warning.
Probably in future we will be able to substitute variable value when possible, since less/sass variables are static.

**Comment by lahmatiy** [comment]
Try out [1.0.6](https://github.com/csstree/stylelint-validator/releases/tag/v1.0.6). Should be fine now.

**Comment by KarolAltamirano** [comment]
@lahmatiy I'm still seeing an error in Sass when there is a variable definition, i.e. `$color01: #eee;`

```
2:1  ✖  Unknown property: $color01        csstree/validator
3:1  ✖  Unknown property: $color02        csstree/validator
4:1  ✖  Unknown property: $color03        csstree/validator
```

could you please have a look.

Thanks a lot.

**Comment by lahmatiy** [comment]
@KarolAltamirano It's another issue. I don't know why a var declaration treats as regular declaration. Can you fill an issue?

**Comment by KarolAltamirano** [comment]
@lahmatiy thanks for your fast reply, I've just created new issue #4
