### ISSUE TITLE
Unknown property `font-display` v1.9.0

### ISSUE THREAD

**Issue by playhardgopro** [csstree/stylelint-validator#30]
Hi! Thank you guys for creating this awesome plugin :)

I read in [this issue](https://github.com/csstree/csstree/issues/48) that the 'css-tree' validates the `font-display` correctly. The VS Code plugin does work correctly, but the `stylelint-csstree-validator` plugin returns error: **Unknown property `font-display`**

I use the latest version: `stylelint-csstree-validator: ^1.9.0`

![image](https://user-images.githubusercontent.com/44134362/108380097-95532300-7217-11eb-9771-c25ca459e337.png)

Could you help, please?

**Comment by lahmatiy** [comment]
`stylelint-csstree-validator` plugin has its own validation implementation which lacks of at-rule validation. This sort of validation will be available in next release pretty soon.

**Comment by lahmatiy** [comment]
Fixed in [2.0.0](https://github.com/csstree/stylelint-validator/releases/tag/v2.0.0) as well as support for at-rule validation
