### ISSUE TITLE
Can't parse value from sass module namespace 

### ISSUE THREAD

**Issue by a9052681569** [csstree/stylelint-validator#39]
I'm using scss module's @use syntax. 

When I "@use" module, I have to access its variables with namespace, like this

![image](https://user-images.githubusercontent.com/50239209/132809514-267cac70-7585-4fb7-93a8-a95fbd709d15.png)

When I do so with mixins or variables, like on screenshot - there's no problem.

But when I want to use that variable in selector property - linter throws error

![image](https://user-images.githubusercontent.com/50239209/132809592-fa63686b-6542-4df3-ad5b-d13d2c73f6df.png)

Error:
![image](https://user-images.githubusercontent.com/50239209/132809756-c6296b23-967e-43ad-a189-9425e1ee9f7c.png)

App builds normally.

What can be done in order for the validator to recognize this?

**Comment by lahmatiy** [comment]
The validator can't recognize it as it can only validate CSS. The validator currently detects some Saas / Less specific syntax and ignores such values. But in this case, it didn't recognize that the value was not CSS. I don’t know why at the moment. As a workaround for now you may try [ignoreValue](https://github.com/csstree/stylelint-validator#ignorevalue) option in plugin's config to suppress warnings for such values, e.g. a value that contains `$` (don't forget escape `$` with a tripple `\`).
