### ISSUE TITLE
Sass variables definition

### ISSUE THREAD

**Issue by KarolAltamirano** [csstree/stylelint-validator#4]
I've tried to use the plugin to lint Sass files (scss syntax) but the plugin is showing an error on each line where there is a variable definition i.e. `$color01: #eee;`

```
2:1  ✖  Unknown property: $color01        csstree/validator
3:1  ✖  Unknown property: $color02        csstree/validator
4:1  ✖  Unknown property: $color03        csstree/validator
```

It seems working fine for variables defined inside mixins. 

This is the list of all plugins that I'm currently using:
```
"plugins": [
        "stylelint-scss",
        "stylelint-order",
        "stylelint-declaration-use-variable",
        "stylelint-csstree-validator"
    ]
```

Thank you!!

**Comment by lahmatiy** [comment]
`1.1.0` is published. Should be ok now.

**Comment by KarolAltamirano** [comment]
Awesome, thank you very much!! 😃
