### ISSUE TITLE
Support for CSS wide keyword "revert"

### ISSUE THREAD

**Issue by aakashgill** [csstree/stylelint-validator#48]
Hi,

I'm using stylelint-csstree-validator plugin, but on using the CSS property "display: revert", 
I'm getting the error "Invalid value" for display. 
But this property works in some browser.

Attached the screenshot of package.json file and the error that I'm getting

![image](https://user-images.githubusercontent.com/8060831/181595151-86b28f89-108c-4f3a-ad76-590d6dd9230a.png)

![image](https://user-images.githubusercontent.com/8060831/181595844-0a9081c5-b4c9-4580-a604-d5fc7db64aa7.png)

![stylelint-tree-validation-error](https://user-images.githubusercontent.com/8060831/181594804-91f581d4-7f71-4267-b016-65f5d3008ebd.png)

Can anyone help regarding this?

Thanks

**Comment by aakashgill** [comment]
Hi,

I'm using stylelint-csstree-validator plugin, but on using the CSS property "display: revert", 
I'm getting the error "Invalid value" for display. 
But this property works in some browser.

Attached the screenshot of package.json file and the error that I'm getting

![image](https://user-images.githubusercontent.com/8060831/181595151-86b28f89-108c-4f3a-ad76-590d6dd9230a.png)

![stylelint-tree-validation-error](https://user-images.githubusercontent.com/8060831/181594804-91f581d4-7f71-4267-b016-65f5d3008ebd.png)

Can anyone help regarding this?

Thanks

**Comment by lahmatiy** [comment]
Update `css-tree` to [2.2.0](https://github.com/csstree/csstree/releases/tag/v2.2.0), should work.

**Comment by lahmatiy** [comment]
Fixed in [2.1.0](https://github.com/csstree/stylelint-validator/releases/tag/v2.1.0)
