### ISSUE TITLE
css modules properties

### ISSUE THREAD

**Issue by trainiac** [csstree/stylelint-validator#5]
Thanks for working on this.

I've seen two other issues for handling Sass and less variables so I thought I might also add special css module properties are also throwing validation errors.

client/components/core/SignOutMenu.vue
 4:3  ✖  Unknown property: composes  csstree/validator

Any chance of supporting css modules features?

**Comment by lahmatiy** [comment]
Yep, syntax will be extensible. So adding css modules support will be possible. Unfortunately we need some time to do it.
I think at this moment single simple solution is adding `ignore` option to the plugin.

**Comment by lahmatiy** [comment]
With [1.1.0](has been published) you now can define a list of property names that should be ignored by the validator.

```json
{
  "plugins": [
    "stylelint-csstree-validator"
  ],
  "rules": {
    "csstree/validator": {
      "ignore": ["composes"]
    }
  }
}
```

Not a perfect solution. But better than nothing.

In future we will be able to extend syntax and even validate extensions like css modules.

**Comment by lahmatiy** [comment]
Since [1.9.0](https://github.com/csstree/stylelint-validator/releases/tag/v1.9.0) became possible to extend syntax definition with `types` and `properties` options.

So you may add definition for `compose` property and others like so:

```json
{
  "plugins": [
    "stylelint-csstree-validator"
  ],
  "rules": {
    "csstree/validator": {
      "properties": {
        "composes": "<custom-ident>+ [ from [ <string> | global ] ]?"
      }
    }
  }
}
```
