### ISSUE TITLE
Stylelint 15 support

### ISSUE THREAD

**Issue by limonte** [csstree/stylelint-validator#54]
> warning "stylelint-csstree-validator@2.1.0" has incorrect peer dependency "stylelint@>=7.0.0 <15.0.0".

**Comment by rgant** [comment]
#53

**Comment by limonte** [comment]
Good news!

You don't actually need `` anymore, there's a built-in rule in Stylelint 15: [`declaration-property-value-no-unknown`](https://stylelint.io/migration-guide/to-15/#added-declaration-property-value-no-unknown-rule)

Here's what I did for my projects: https://github.com/sweetalert2/stylelint-config/commit/b17a7f48ca2608360aabffacfd591988e5f3b1a9

**Comment by lahmatiy** [comment]
Very sorry in delay for an update. That's fixed in [v3.0.0](https://github.com/csstree/stylelint-validator/releases/tag/v3.0.0). The fix is also required to drop older versions of Node.js, that's why it's a major version bump due to semver.
