### ISSUE TITLE
sass interpolation

### ISSUE THREAD

**Issue by danpoltawski** [csstree/stylelint-validator#7]
Slightly related to #4, I've found our codese problems coming from [sass interpolation]( http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_)
```
.navbar-static-top .dropdown .dropdown-menu {
    max-height: calc(100vh - #{$navbar-height});
    overflow-y: auto;
}
```

```
>> theme/boost/scss/moodle/undo.scss
>>  138:5  ✖  Can't parse value "calc(100vh - #{$navbar-height})"   csstree/validator
```

Thanks for this project!

**Comment by lahmatiy** [comment]
Try out [1.1.1](https://github.com/csstree/stylelint-validator/releases/tag/v1.1.1). Issue should be fixed.

**Comment by danpoltawski** [comment]
Thank you for such prompt work!
